ports:
  - port: 1080
    onOpen: open-preview
    description: docker-compose
    visibility: public

# This will make it so that on workspace start it will run a file called `app.py`
tasks:
  - init: docker-compose up
